# Generated by Django 3.2.5 on 2021-07-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plajamea_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('total', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plajamea_web.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Umbrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seats', models.IntegerField()),
                ('umbrella_number', models.IntegerField()),
                ('is_occupied', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='table',
            name='umbrella_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plajamea_web.umbrella'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plajamea_web.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plajamea_web.table'),
        ),
    ]
