# Generated by Django 3.2.5 on 2021-07-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plajamea_web', '0002_auto_20210724_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='WaitedTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plajamea_web.table')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plajamea_web.waiter')),
            ],
        ),
    ]
